# OpenAPI v3 Training Exercise
# © 2019 ModelSolv Inc. All rights reserved.

openapi: "3.0.0"
info:
  version: 1.0.0
  title: RepreZen API Workshop Series
  description: |
    # Exercise: Validating Properties
    
    This document contains a single object schema definition.
    
    Adjust the schema so that the first object instance is valid,
    and the second one is not.
    
    ## Valid Instance
    ```
    {
      "accountID" : "ASDF1234",
      "customerID" : "987-89-2345",
      "branch" : "CLARKSVILLE_987"
      "dateOpened" : "2017-04-10",
      "balance" : "10782.53",
      "isJointAccount" : false
    }
    ```
    
    ## Invalid Instance      
    ```
    {
      "accountID" : "ASDF1234",
      "customerID" : "987-89-2345",
      "lastStatement" : "2019-03-16"
      "branch" : "CLARKSVILLE_987"
      "dateOpened" : "2017-04-10",
      "balance" : "10782.53",
      "isJointAccount" : false,
      "overdraftLimit" : 15000
    }
    ```
    
paths: {}

components:

  schemas:

    DepositAccount:
      type: object
      required:
        - accountID
        - customerID  
      properties:
        accountID:
          description: Unique identifier for this account.
          type: string
        customerID:
          description: ID of the account owner's customer record.
          type: string
        branch:
          description: Bank branch servicing the account.
          type: string
        dateOpened:
          description: Date when the account was opened.
          type: string
          format: date
        currentBalance:
          description: Balance in the account's designated currency.
          type: number
          format: double
        isJointAccount:
          description: |
            `true` if the account has more than one owner,
            otherwise `false`. 
          type: boolean
      additionalProperties: false
